name: Android APK
on: [push]

env:
  PROJECT_DIR: weight-ean-scanner_v1_2   # ← ИМЯ ТВОЕЙ ПАПКИ (замени!)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: true

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Download Gradle 8.7
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$GITHUB_WORKSPACE/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: gradle clean :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
